### ISSUE TITLE
Class 'LinkTitles\Title' not found

### ISSUE THREAD

**Issue by jmcquillan** [bovender/LinkTitles#10]
When trying to run LinkTitles_Maintenance.php from the command line, I get the error below:

PHP Fatal error:  Class 'LinkTitles\Title' not found in mediawiki/extensions/LinkTitles/LinkTitles_Maintenance.php on line 146

How is the cli script run in v4?

**Comment by bovender** [comment]
This project really needs an automatic test suite...
