### ISSUE TITLE
Multiple links even with LinkTitlesFirstOnly 

### ISSUE THREAD

**Issue by jmcquillan** [bovender/LinkTitles#12]
I have an existing page titled 'Test'.  I created a new page titled 'Test Page' with the content 'Test Page Test Page Test Page Test Page Test Page Test Page'

The content ended up with '[[Test Page]] [[Test Page]] [[Test]] Page [[Test]] Page Test Page Test Page'

'Test Page' and 'Test' are each linked twice instead of once each.

**Comment by bovender** [comment]
That one is fixed.

What's odd though is the Wiki markup that you show above:

> The content ended up with '[[Test Page]] [[Test Page]] [[Test]] Page [[Test]] Page Test Page Test Page'

Because that suggests the page is linked back to itself. The extension should prevent this, and in fact, on my system it doesn't happen. Is this a typo, or another issue?

**Comment by jmcquillan** [comment]
Looks like another issue.  It seems to always create links to itself for me... I thought that was the 'normal' behavior, but it would be nice if it were fixed.

**Comment by jmcquillan** [comment]
There still seems to be a problem with this.  If I started with the same setup as originally described, then run the command line Maintenance Script on this page, the first time will return the expected result of:

> [[Test Page]] [[Test]] Page Test Page Test Page Test Page Test Page test page test page test page test page test page test page

but if I then run the same command again, it will change the content to:

> [[Test Page]] [[Test]] Page [[Test Page]] [[Test]] Page Test Page Test Page test page test page test page test page test page test page

(with multiple links)

**Comment by bovender** [comment]
That is in fact an issue with the extension logic. The `$wgLinkTitlesFirstOnly` option works by limiting the number of links that are inserted in one pass. Currently the extension does not check at all whether a given page contains a link to a certain other page already. I see however that this is what one might expect: If the page has a link to 'X' already, don't turn other occurrences of 'X' into links.

The extension would have to search the page text for links (both plain links and 'piped' links) for a link before inserting another one. I need to think about how to implement this without too much of a performance impact.

**Comment by jmcquillan** [comment]
Maybe add a flag so it the user can choose to accept (or not) the performance hit?
