### ISSUE TITLE
Namespace weight unused in parseContent()

### ISSUE THREAD

**Issue by labster** [bovender/LinkTitles#15]
I don't know what the point of the namespace weight is supposed to be, but I can tell that it isn't being used at all.  Is that some sort of future functionality expansion, leftover code cruft, or is that just making the DB do more work for no particular reason?  If you want, I can make a PR to remove it.

**Comment by bovender** [comment]
Hm. Maybe @c0nnex  could comment on this?

**Comment by c0nnex** [comment]
hmm it should be used, I'll dig in my old sources , maybe forgot to checkin that part.... 
It's for deciding in which order namespaces are checked, so you can favor one namespace over another (e.g. Glossar: is checked first before Manual: is checked)

**Comment by c0nnex** [comment]
Just checked .. in the namespaces branch I submitted it's used...
https://github.com/c0nnex/LinkTitles/blob/namespaces/LinkTitles.body.php 172ff

**Comment by bovender** [comment]
OK, so I messed up somehow. I'll look into it.

**Comment by labster** [comment]
Oh right, this line:

https://github.com/c0nnex/LinkTitles/blob/namespaces/LinkTitles.body.php#L209

That makes a difference.
