### ISSUE TITLE
$wgLinkTitlesBlackList not working

### ISSUE THREAD

**Issue by dwhagar** [bovender/LinkTitles#20]
So, I have some common words, I don't want auto-linked.  They are redirects, so the magic word never seems to work.  I'd rather not remove them because they can make things a lot easier to have these words redirected.  I don't want every occurrence of these words to be linked though, I will link them myself if I want to use them.  However, I can't get the magic word nor the blacklist variable to work.

Here is my code in LocalSettings pertaining to this:
`$wgLinkTitlesBlackList[] = 'Done';`
`$wgLinkTitlesBlacklist[] = 'drone';`
`$wgLinkTitlesBlackList[] = 'Drones';`
`$wgLinkTitlesBlackList[] = 'drones';`
`$wgLinkTitlesBlackList[] = 'Federation';`
`$wgLinkTitlesBlackList[] = 'federation';`

**Comment by dwhagar** [comment]
Nevermind, it was my fault.

**Comment by bovender** [comment]
OK, no problem. Let me know if you find bugs.
