### ISSUE TITLE
Linking in Image Galleries / Exclusion Tags

### ISSUE THREAD

**Issue by dwhagar** [bovender/LinkTitles#21]
I don't think that the extension should link to text within a <gallery></gallery> block.  If you've got a page called, say, "Ruth", and do an image in a gallery say, File:Baby-Ruth.jpg, then it will become File:Baby-[[Ruth]].jpg which will completely screw up the image.

I also think there should be some kind of tag, similar to <nowiki> so that a block of text, but not the whole page, can be exempted from being scanned to link.  Just a thought.

**Comment by bovender** [comment]
Can you please post some example code for the 'Ruth' case? The extension takes care of several types of blocks already, so adding another one should not be a problem.

I need to think about something like `<nolinks>...</nolink>`.
