### ISSUE TITLE
Not listening to __NOAUTOLINKS__ when rendering.

### ISSUE THREAD

**Issue by dwhagar** [bovender/LinkTitles#23]
If the option `$wgLinkTitlesParseOnRender = true;` is set, when a page is rendered, it does not listen to the `__NOAUTOLINKS__` magic word and renders link titles.

**Comment by bovender** [comment]
Thanks, I'll look into it, as well as the other issues. Just a little short on time at the moment, please bear with me.

**Comment by dwhagar** [comment]
You're fine I have some gits that haven't seen attention in a while! :)

**Comment by bovender** [comment]
Finally fixed it.

Closed by aa8b16322829bbe03762aff87f832b52937e0070.
