### ISSUE TITLE
Call to undefined method WikiPage::doQuickEditContent()

### ISSUE THREAD

**Issue by ns55** [bovender/LinkTitles#24]
When LinkTitles_Maintenance.php is executed with MediaWiki 1.28, the following error occurs.

Error: LinkTitles_Extension.php: Call to undefined method WikiPage::doQuickEditContent()

"WikiPage :: doQuickEditContent ()" has been deleted in 1.28

**Comment by bovender** [comment]
Thanks for pointing this out. I was wondering why the maintenance script crashed on my production wiki. It did not occur to me that the function simply did not exist any more...
