### ISSUE TITLE
Titles not being linked 

### ISSUE THREAD

**Issue by midgethoen** [bovender/LinkTitles#25]
Hi there,

I've been having some issues with a page where some titles are not being linked as expected.
I have tried to debug the issue but I wasn't having much luck so far so I thought I'd ask for tips here first.

this is the (stripped) text in mention: [wikitext.txt](https://github.com/bovender/LinkTitles/files/842687/wikitext.txt)

the word that I expect to be linked is `Katernen`. I have allready quadruple checked if that page exists and even logged the list of querried titles in the routine to be sure it's retrieved.

It seems to have some thing to do with the table on te page.

Help would be greatly appreciated

**Comment by bovender** [comment]
I can confirm this on my local Wiki. It's got something to do with the `<span>...</span>` tags inside the headings. Once you remove them the page is linked. The page is also linked if there are `span`s outside of headings.

I need more time to debug this.

**Comment by midgethoen** [comment]
Thanks for your quick reply. 
I might find some time to look into this further in the future.

**Comment by midgethoen** [comment]
I just realised that I tried removing the span's from titles without result. I also had success WITH the spans when I removed the table. So, something else might be going on..

**Comment by bovender** [comment]
@midgethoen Do you still experience this issue? On occasion of the complete rewrite and release of version 5 of the add-in, I ran your [wikitext.txt](https://github.com/bovender/LinkTitles/files/842687/wikitext.txt) through my local testbed installation, and it works as expected.

I'd close this issue unless it still does not work for you.
