### ISSUE TITLE
Ability to disable link inside preformatted text

### ISSUE THREAD

**Issue by blacksails** [bovender/LinkTitles#26]
In our wiki we would like LinkTitles to skip all preformatted text.

That doesn't seem to be possible at this time. Or am I missing something?

**Comment by bovender** [comment]
How do you mark up your preformatted text, with `<pre>` `</pre>` tags, or a leading space on every line?

Both work fine for me. Evidently there must be a subtle bug.

**Comment by blacksails** [comment]
I just did some testing and it seems that this is not an issue in the most recent version. 

I recently updated our wiki and all of it's extensions so it might have been fixed in that update.
