### ISSUE TITLE
preg_replace_callback(): Compilation failed: missing )

### ISSUE THREAD

**Issue by Sabku** [bovender/LinkTitles#28]
Hi,

ich nutze MW 1.23.15 und die (so denke ich zumindest) dazu passende LinkTitles Version 2.2.

Ich habe 2 bis auf den Inhalt der DB identische Wikis. Bei dem einen funktioniert die Extension ohne Probleme bei dem anderen leider nicht. Sobald ich sie aktiviere und im Wiki testen möchte erhalte ich diese Fehler:
PHP Warning:  preg_replace_callback(): Compilation failed: missing ) at offset 97 in /wiki/extensions/LinkTitles/LinkTitles.body.php on line 206, referer: http://wiki/...
PHP Warning:  preg_replace(): Compilation failed: missing ) at offset 106 in /wiki/extensions/LinkTitles/LinkTitles.body.php on line 186, referer: http://wiki/...

Hat jmd. eine Idee?

Gruß
Sabku

**Comment by bovender** [comment]
Hi Sabku,

laufen beide Wikis mit derselben PHP-Version?

Daniel

**Comment by Sabku** [comment]
Hi Daniel,

sorry für die späte Antwort.
Ja die Systeme sind auf dem exakt selben Stand.
Hier nochmal alle Details:
RedHat 7.3
php 5.4.16
MW 1.23.15
LinkTitles Version 2.2

Gruß,
Sabrina

**Comment by bovender** [comment]
Hallo Sabrina,

kann es sein, daß in dem einen Wiki, wo es nicht geht, Seiten mit "komischen" Zeichen vorkommen? Bspw. Klammern oder Backslashes.

Eine schnelle Reparatur könnte darin bestehen, die Datei `LinkTitles.body.php` in einem Texteditor zu öffnen und Zeile 164 zu ändern:

Alt:

    LinkTitles::$safeTitle = str_replace( '/', '\/', $title );

Neu:

    LinkTitles::$safeTitle = preg_quote($title, '/');

Wahrscheinlich ist es einfacher, Du probierst es aus, als wenn ich einen eigenen Branch erstelle, den Du ja dann auch erst ziehen müßtest. Wenn das funktioniert, kann ich gerne ein Update machen. Aber noch besser wäre es natürlich, eine aktuelle Version zu verwenden ;-) Geht natürlich nur mit neueren MediaWiki-Versionen (1.25 und neuer).

Viele Grüße,

Daniel

**Comment by Sabku** [comment]
Hallo Daniel,

du bist mein Held. Vielen Dank!
Nun geht es. Ich hatte auch schon selbst rumprobiert aber nun ja ich bin Admin  und kein Entwickler. Und ja genauso stellte sich der Fehler dar.
Mit der MediaWiki Version hast du natürlich recht. Nur leider bin ich an die PHP Version gebunden und das zieht sich dann bis zu LinkTitles durch.

Gruß,
Sabrina

**Comment by bovender** [comment]
Hallo Sabrina,

diesen Fehler hatte ich in Version 2.3.0 einmal repariert. Wenn mich nicht alles täuscht, müßte doch 2.3.x auch noch mit der alten MediaWiki-Version funktionieren?

Ansonsten ist ja gut, wenn es mit dem Edit jetzt geht.

Viele Grüße

Daniel

**Comment by Sabku** [comment]
Hallo Daniel,

das werde ich mir gleich mal ansehen.
Danke für den Tip :)

Gruß
Sabrina
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 24.06.17, 14:57, Daniel Kraus <notifications@github.com> schrieb:
Hallo Sabrina,
diesen Fehler hatte ich in Version 2.3.0 einmal repariert. Wenn mich nicht alles täuscht, müßte doch 2.3.x auch noch mit der alten MediaWiki-Version funktionieren?
Ansonsten ist ja gut, wenn es mit dem Edit jetzt geht.
Viele Grüße
Daniel
