### ISSUE TITLE
Call to undefined method WikiPage::doQuickEditContent()

### ISSUE THREAD

**Issue by Ikabodo** [bovender/LinkTitles#30]
Hello!

I'm getting this error with the script on the special page. Any clue what could cause it?

```
[ab1ff616fb76c7eca93ce370] /index.php?title=Special:LinkTitles Error from line 272 of /customers/0/6/c/ikabodo.se/httpd.www/w/extensions/LinkTitles/LinkTitles.body.php: Call to undefined method WikiPage::doQuickEditContent()

Backtrace:

#0 /customers/0/6/c/ikabodo.se/httpd.www/w/extensions/LinkTitles/SpecialLinkTitles.php(128): LinkTitles::processPage(string, RequestContext)
#1 /customers/0/6/c/ikabodo.se/httpd.www/w/extensions/LinkTitles/SpecialLinkTitles.php(61): SpecialLinkTitles->process(WebRequest, OutputPage)
#2 /customers/0/6/c/ikabodo.se/httpd.www/w/includes/specialpage/SpecialPage.php(522): SpecialLinkTitles->execute(NULL)
#3 /customers/0/6/c/ikabodo.se/httpd.www/w/includes/specialpage/SpecialPageFactory.php(577): SpecialPage->run(NULL)
#4 /customers/0/6/c/ikabodo.se/httpd.www/w/includes/MediaWiki.php(283): SpecialPageFactory::executePath(Title, RequestContext)
#5 /customers/0/6/c/ikabodo.se/httpd.www/w/includes/MediaWiki.php(851): MediaWiki->performRequest()
#6 /customers/0/6/c/ikabodo.se/httpd.www/w/includes/MediaWiki.php(512): MediaWiki->main()
#7 /customers/0/6/c/ikabodo.se/httpd.www/w/index.php(43): MediaWiki->run()
#8 {main}
```

*Additional info:*
Not sure if is related, but I'm getting a 500 error when using:
```wfLoadExtension( 'LinkTitles' );```

The extension works when i use:
```require_once( "$IP/extensions/LinkTitles/LinkTitles.php" );```

Edit: formatting

**Comment by Ikabodo** [comment]
I managed to find the issue. It was a corrupted installation. Reinstalling fixed the issue.

**Comment by SC-JBG** [comment]
Hi @Ikabodo,

could you elaborate on how you fixed the issue and what the cause of it was? I am having the exact same issue: Autolinking after editing a single page works, loading the extension via wfLoadExtension throws a 500 exception and the special page does not work at all throwing exactely the exception from your initial post.

Would love to hear your thoughts on that!

Best,
Julian

**Comment by bovender** [comment]
@SC-JBG Are you positive you're on the latest release?

If so, is there anything in the server logs that could help with the 500 issue. Also, when you say the special page throws exactly the same exception, could you please tell me the file name and line number where the error occurs (because that has definitively changed since July).

Kind regards

Daniel

**Comment by SC-JBG** [comment]
Hey @bovender,

man dude you're fast! Cool thing :)

Well, I downloaded the release package over the mediawiki website, following the link to this release zip: https://github.com/bovender/LinkTitles/archive/v5.0.3.zip and after re-checking just a sec ago I see that the .tar.gz which is within the /release folder of that zip contains a package called: LinkTitles-3.0.1.tar.gz - which, at least from a version number perspective, looks old to me. 

The actual issue happens here:

**LinkTitles.body.php (Line 272)**
`
$page->doQuickEditContent($content,
	$context->getUser(),
	"Links to existing pages added by LinkTitles bot.",
	true // minor modification
);
`

After replacing that code with code from your dev-branch as below everything works smoothly:

`
$page->doEditContent(
	$content,
	"Links to existing pages added by LinkTitles bot.", // TODO: i18n
	EDIT_MINOR | EDIT_FORCE_BOT,
	false, // baseRevId
	$context->getUser()
);
`

Does that help?

**Comment by bovender** [comment]
OK @SC-JBG That 3.0.1 file should not be there... Clearly an error with the repository management that I missed.

Just extract the folder that is contained in the release ZIP into your extensions folder, rename it to "LinkTitle" (so it does not carry the version tag) and you should be all set!

Let me know if it does not work.

**Comment by SC-JBG** [comment]
Hey @bovender,

hopefully I do not get something wrong here - but that's what I did. I downloaded the release package from this URL: https://github.com/bovender/LinkTitles/archive/v5.0.3.zip

Then, I switched to the /release directory within that package and extracted a file called "LinkTitles-3.0.1.tar.gz". I took the folder "LinkTitles" within that archive and pushed it to my /extensions directory within my mediawiki installation.

But all files within that package are timestamped to 2014 - so they look quite old.

The change I made so far was to simply change the code above with updated code from your development branch here. Now everything works but seems to be a bit odd.

Could you give me a ping once you checked the release package and uploaded a fixed version? That would be really nice!

Thank you, and overall thank you for that extension - in my opinion this is one of the most useful tools for a wiki ever.

Cheers,
Julian

**Comment by bovender** [comment]
@SC-JBG what I meant to say was that the release ZIP file `v5.0.3.zip` contains all the files of the extension, *plus* an erroneous additional `release/` directory. So you could have just extracted the contents of the ZIP file into your `extensions` directory. Don't let yourself be confused by the fact that GitHub says 'source code'. In the case of a PHP script, the source code is the same as the executing code.

However, 5.0.3 contained a bug that would prevent linking on many pages that are a bit more complex. So I recommend you download version 5.0.4 that I released just now, which does not contain the additional directory.

Hope this helps!

Schönes Wochenende,

Daniel
