### ISSUE TITLE
Tags get added each time a page is edited and saved. 

### ISSUE THREAD

**Issue by Ikabodo** [bovender/LinkTitles#33]
After the great update that added autolink tags things are looking fine, but I think I've found a bug.

It adds [[]] every time you save the page. Causing issues like [[[[[[Roderick]]]]]] if the page is updated several times. It appears it only happens if within {{}}.

I'm guessing the new regex does not check for existing [[]]?

Edit: After some research, I'm getting some strange behavior. I'm getting the feeling it starts parsing after a certain length of text.  Could this be it? What it's doing is adding more and more [[]] if $wgLinkTitlesSkipTemplates = true; and there is a lot of text. 

http://w.ikabodo.se/index.php?title=Test3

Here is an example, according to me this page should not parse with $wgLinkTitlesSkipTemplates = true;, but it seems to be doing it. At least partly. It's an extreme example with a lot of text, but it's just for testing. Compare the first text around "463" to the second text with the same number further down. It's the exact same text, the first is parsing, the lower part is not. It's behaving as if only parsing the first word, but according to me should not parse at all.

**Comment by bovender** [comment]
Hm, I have implemented automatic tests in the past couple of days, and in the tests it works as expected:

    This text has a {{template|with=already linked [[link target]]}} in it

When I run this text through the tests, I don't get additional `[[]]`'s.

Can you please provide a concrete example that I can use in the automated tests? (It might also be that I inadvertently fixed a bug during the major rewrite that is currently under way.)

**Comment by Ikabodo** [comment]
The link in the first articles is a concrete example. You should be able to see the source code, if not. I can give you a login to the wiki to check yourself. Since there is a lot of text that seems to cause it, I think it's a bit difficult to paste the code here.

http://w.ikabodo.se/index.php?title=Test3

**Short version:**
I call this template:
```
{{CharacterSections
|Linetime='''471:''' Together with Melkin, had an adventure with the [[[[Redcap]]]] in Mordron’s [[[[forest]]]].
}}(a lot of text, wiki-formatted)
```
The template looks like this:
```
{{#ifeq:{{{Linetime|}}}|||
== Timeline ==
{{{Linetime|}}}
```

**My settings are:**
$wgLinkTitlesSkipTemplates = true;
$wgLinkTitlesParseHeadings = false;

**Comment by bovender** [comment]
Are you on the latest commits of the `develop` branch when you see this behavior? Just so I know where to look in the code.

**Comment by Ikabodo** [comment]
I just downloaded commit 4a92321. 

I'm doing some testing, but it seems it is working now.

**Comment by Ikabodo** [comment]
A followup question:
Is `<autolink>` intended to only parse on view? and not on edit?

**Comment by bovender** [comment]
> Is `<autolink>` intended to only parse on view? and not on edit?

Yes, that's how MediaWiki's tags work.
