### ISSUE TITLE
noautolinks and nowiki

### ISSUE THREAD

**Issue by ricmetal** [bovender/LinkTitles#39]
setting noautolinks before a nowiki tag. shouldn't the noautolinks **not** create any brackets [[]] nowiki the nowiki tag?

**Comment by ricmetal** [comment]
ok, i'm too used to auto updating software. my bad. 
there's a typo btw in the NEWS file, in Version 5.0.0 (2017-09-01), you use the tag <autolink>, and not <autolinks>.
thanks

**Comment by bovender** [comment]
Glad it was solved so easily.

Thanks for pointing out the typo. The NEWS file is auto-generated from Git commit messages, so I won't be able to fix it without rewriting a lot of history; but luckily the README has the correct information.
