### ISSUE TITLE
No Title Linking on Edit

### ISSUE THREAD

**Issue by calebfergie** [bovender/LinkTitles#43]
Hi there,

I've installed LinkTitles on my wiki - the batch linker works great, but I can't seem to get it to link on edits. For example, after editing [this page](https://ncp-wiki.herokuapp.com/index.php?title=Send_it_again), text like _"Send it"_ and _"SciWing"_ should link automatically, right? 

Here is my [code repo](https://github.com/calebfergie/NCP-Wiki), with the project deployed [here](thesis.calebfergie.com).

I took a look through the configuration settings and everything seems to check out (all in the `NS-MAIN` namespace, etc.) As such my `LocalSettings.php` has the following:

```## Auto-Linker - generates links to existing pages when pages are created or edited
## Needs to have minor checkbox edit undefaulted - but breaks button links, so disabling for now
$wgDefaultUserOptions['minordefault'] = 0;
wfLoadExtension( 'LinkTitles' );
### Autolinker configuration
#### remove case sensitivity with smart mode
$wgLinkTitlesSmartMode = true;
```

I know this is an older project but would appreciate any tips on this!

I'm new to wiki/PHP so let me know if you could use any other info.

**Comment by bovender** [comment]
Hm, that's a hard one. I could not get it to automatically link anything on your wiki either. What's going on here? Does it have to do with the 1.33-alpha version of MediaWiki? Or is any of the other extensions interfering?

Can you try with version 1.32? Or maybe it is easier to disable all extensions but 'LinkTitles', then see if it works, then re-enable the other extensions one at a time. If it does not work even with all other extensions disabled, it must have something to do with the MediaWiki version?

I did try to edit one of your pages with `&action=edit` in the URL, in order to avoid the TinyMCE editor. But that was not a solution either.

**Comment by calebfergie** [comment]
Thanks for getting back to me. It would be tough for me to try with a different version so I'll try disabling extensions.

 If it works with other extensions, do you have any ideas about which extensions may be the culprit? I agree that the TinyMCE editor may be the culprit, but here are some others I'm using:

* [WikiEditor](https://www.mediawiki.org/wiki/Extension:WikiEditor)
* [Tweeki skin](https://github.com/thaider/Tweeki)
* [AWS Extension](https://www.mediawiki.org/wiki/Extension:AWS)
* [InputBox](https://gerrit.wikimedia.org/g/mediawiki/extensions/InputBox)
* [Breadcrumbs](https://www.mediawiki.org/wiki/Extension:BreadCrumbs) & [HistoryLink](https://www.mediawiki.org/wiki/Extension:BrowserHistoryLink)
* [Preloader](https://www.mediawiki.org/wiki/Extension:Preloader)
* [Variables](https://www.mediawiki.org/wiki/Extension:Variables), [ParserFunctions](https://www.mediawiki.org/wiki/Help:Extension:ParserFunctions) and [URLGetParameters](https://www.mediawiki.org/wiki/Extension:UrlGetParameters)
* [EmbedVideo](https://www.mediawiki.org/wiki/Extension:EmbedVideo) and [HTMLTags](https://www.mediawiki.org/wiki/Extension:HTML_Tags)
* [SpamRegex](https://www.mediawiki.org/wiki/Extension:SpamRegex)

**Comment by bovender** [comment]
Incidentally I set up a new Wiki myself, using version 1.32, and LinkTitles does not work either. So at least it's reproducible now, I'll have to investigate further...

**Comment by calebfergie** [comment]
Yup, can confirm after removing most extensions it still wasn't working.

Thanks for looking into it. LinkTitles would be a great addition to my project.

**Comment by bovender** [comment]
MediaWiki 1.32 changed the way it passes the content of a page to extensions while an edited page is being saved (`PageContentSave` hook). It now discards any modifications to the page content.

There's an ongoing discussion about this here: https://phabricator.wikimedia.org/T222413

It appears that MediaWiki 1.32 is fundamentally incompatible with the LinkTitles extension :-( I'm hoping to get some pointers from the MediaWiki developers as to how the page content could still be altered by an extension, as I am currently not aware of alternatives to `PageContentSave`.

**Comment by calebfergie** [comment]
Thank you looking into it. Darn fundamental changes. I'll close this issue now.

**Comment by Arthaey** [comment]
Would the client-side-only functionality of this extension (auto-linking _without_ modifying the saved content) still work in 1.32?

**Comment by bovender** [comment]
Yeah, that should still work. Furthermore, it is possible to use the command-line interface to go through all pages and add links, e.g. using a cron job that runs in the middle of the night.

I was in touch with the MW developers. Overall it does not seem to be straightforward to add back the 'add links when a page is saved' functionality. However, I also have not yet had the time to try out one possibility that was pointed out to me.

**Comment by paladox** [comment]
This is fixed with https://github.com/bovender/LinkTitles/pull/53
