### ISSUE TITLE
linktitles-cli.php

### ISSUE THREAD

**Issue by wawaks** [bovender/LinkTitles#48]
Hi!
Linker is great. I use it for some years. As my website has several thousand pages I use mainly linktitles-cli.php and it works very nice.

There is some improvement possible in that script. In line 171 there is:
`$numPages = $res->numRows();`
If someone starts with _-s index_ it returns wrong number of pages and wrong percentage. I think it should be:
`$numPages = $res->numRows() + $index;`
I changed it and now it shows proper numbers.

Another change I made in line 178:
`$this->output( sprintf( "\rPage #%d (%02.0f%%) ", $index, $index / $numPages * 100 ) );`
I added presentation of title of current page, which looks nice:
`$this->output( sprintf( "\rPage #%d (%02.0f%%) %s", $index, $index / $numPages * 100, $title2 ) );`
If the title of next page is shorter than the previous some letters are being left. I solved it by adding some spaces to $title2 variable:
`$title2 = $title."                ";`
and I put it before line 178. Maybe there is better way to do it, but it works. :-)

Thanks again!
Slawek

**Comment by bovender** [comment]
Hi Slawek,

thanks very much. Would you be able to issue a pull request? Against the develop branch, please. If that's not possible for you, please let me know.

Best

Daniel

**Comment by wawaks** [comment]
Unfortunately I don't use/know github. Sorry. :-(

**Comment by bovender** [comment]
> If someone starts with -s index it returns wrong number of pages and wrong percentage. I think it should be:
>     $numPages = $res->numRows() + $index;

Hm, shouldn't the index be subtracted from the number of pages, rather than adding to it...? 🤔

```
$numPages = $res->numRows() - $index;
```

**Comment by wawaks** [comment]
$res->numRows() + $index gives you number of all pages, as the numRows returns only number from index to the last page.

**Comment by bovender** [comment]
After letting this mature for a while I think I'd rather set `$index = 0;` before  displaying the progress.

Still not sure how to best handle the issue with the page title display though.

**Comment by bovender** [comment]
The new `--verbose` option provides a way to know the title of the page that is currently being processed.
