### ISSUE TITLE
UTF8 Error

### ISSUE THREAD

**Issue by BIGRizZ84** [bovender/LinkTitles#5]
Hi bovender,

habe das selbe Problem wie Gerd bereits hier, aber unabhängig vom Seitentitel.
Der Fehler tritt auch auf der Hauptseite auf.

http://www.mediawiki.org/wiki/User_talk:Bovender#LinkTitles_LinkTitles_UTF8_Fehler.3F

Kannst uns bitte helfen das in den Griff zu bekommen?
Wir haben eine Standard SMW Installation laufen.

Danke
MFG
Steffen

**Comment by bovender** [comment]
Hallo Steffen,

probier mal, was passiert, wenn Du in der Zeile Nr. 226 in der Datei `LinkTitles.body.php` das "u" streichst:

    $wordStartDelim . $searchTerm . $wordEndDelim . '/u',

Wird dann zu

    $wordStartDelim . $searchTerm . $wordEndDelim . '/',

Eigentlich müßte das "u" (für Unicode) erforderlich sein, damit die Word-Grenzen-Erkennung funktioniert. Aber ich habe es bei mir auf dem Entwicklungssystem mal gelöscht, und es funktioniert trotzdem alles wie gehabt.

Das Problem ist halt, daß ich diese Fehlermeldung nicht reproduzieren kann, egal, wie ich mein Entwicklungssystem oder auch das Produktiv-Wiki malträtiere. Das macht die Suche nach einer Lösung schwierig -- aber viell. ist das "u" ja die Lösung.

Inzwischen gab es noch eine Nachricht auf der MediaWiki-Seite zum selben Thema, kommt die von Dir, oder ist das zufällig am gleichen Tag jemand anderes gewesen?

Daniel

**Comment by BSG2000** [comment]
Hallo Daniel,
ich hatte gestern das gleiche Problem nach einen Update der mediawiki Installation und Neuinstallation dieser Extension gehabt. Dein Lösungsvorschlag hat auch bei mir funktioniert. Danke dafür.
Gruß Thomas

**Comment by bovender** [comment]
@BSG2000 Danke für die Rückmeldung, ich denke, ich werde das demnächst mal in ein Release einbauen.

**Comment by jmcquillan** [comment]
I was getting a similar warning when running LinkTitles.body.php; changing '/u' to '/' made the warning go away.

Warning: preg_replace_callback(): Compilation failed: invalid UTF-8 string at offset 32 in mediawiki/extensions/LinkTitles/LinkTitles.body.php on line 226

**Comment by bovender** [comment]
Yeah, I think I'll just remove the 'u' flag.
