### ISSUE TITLE
DivisionByZero in Special.php, line 250

### ISSUE THREAD

**Issue by GerardNL** [bovender/LinkTitles#55]
While creating a wiki, I was thinking that it would be so nice to have pages link automatically and was very pleased to find it already exists!

Starting with a rather empty wiki, it seems that $reloads could be 0 which causes an error in this line:
` $pagesPerReload = sprintf('%0.1f', $end / $reloads);`
or at least that's the error I get when running the Special LinkTitles page
A test before the division will solve this error. I'm not skilled enough in PHP to show my code, but I think it's an easy fix for the author?

Thanks for your efforts in creating this extension.

Gerard

**Comment by bovender** [comment]
Thanks for the heads-up, I'll look into this.

By the way, if this is a new wiki with few pages, there's not really a need to do the linking via the special page, you can configure the extension to link pages as you create/edit them.

**Comment by GerardNL** [comment]
> Thanks for the heads-up, I'll look into this.
Thanks. Sometimes these things are hard to find as you can't simulate all environments.
> 
> By the way, if this is a new wiki with few pages, there's not really a need to do the linking via the special page, you can configure the extension to link pages as you create/edit them.
This was a case of RTFW: I was making minor edits to one the pages and nothing happened. So I was trying out the other option just to see if it would pick up the link that way. Later on, I read it only searches for links with major edits...

Anyway, thanks for extension. I'm creating a private wiki in which I will import data. This extension will make life easier for sure!

**Comment by bovender** [comment]
@GerardNL I release v8.0.1 just now, you may want to upgrade ;-)
