### ISSUE TITLE
Link replacement issues with PageForms (ParseOnRender)

### ISSUE THREAD

**Issue by zyzzyxdonta** [bovender/LinkTitles#58]
Hi,

we noticed that LinkTitles doesn't work well with the PageForms extension. With ParseOnRender enabled, it tries to replace words in dropdown menus and placeholder texts in text boxes. Sometimes it works and creates a link (which is still a bit annoying in dropdown menus), other times the replacement fails and it just shows `<!--LINK'" 0:0-->` and the original text is not shown at all. I didn't try ParseOnEdit.

**Comment by bovender** [comment]
Sorry for letting you wait so long. I don't use the PageForms extension. Could you please let me know if this extension adds typical tags to a page? Then I could exclude those from being parsed by LinkTitles.

**Comment by zyzzyxdonta** [comment]
No worries 😄
I think everything is just `<input></input>` and `<select></select>` tags.

**Comment by zyzzyxdonta** [comment]
Thank you! We will test the fix at the next opportunity.
