### ISSUE TITLE
Inserting links to the category namespace breaks the page...

### ISSUE THREAD

**Issue by bertrandgorge** [bovender/LinkTitles#63]
Hello, we configured our wiki to replace links to NS_Main and NS_Category.

When a link is made to a category, say : `this word gets linked` becomes `this [[category:word | word]] gets linked`, the wrong syntax is used. It should read `this [[:category:word | word]] gets linked` (colon at the start of the link).

I saw that having colons at the start of EVERY link doesn't harm (`[[:some title]]` works fine). It could be an option to simplify the fix...?

**Comment by bovender** [comment]
Ah, this is a special case where the namespace is in fact a category. Yes, the link needs to be prefixed with a colon; otherwise, the page would simply be _added_ to the category.

Reference: https://www.mediawiki.org/wiki/Help:Categories#Linking_to_a_category

(BTW I think you meant to write "colon", not "column".)

**Comment by bertrandgorge** [comment]
Yes, exactly. Do you think adding colons everywhere would be too much/messy ? The alternative would be to manage the specific case - I'd be happy to try but not sure where to look at in the code...

**Comment by bertrandgorge** [comment]
Here's the fix too.

**Comment by bertrandgorge** [comment]
Hello @bovender, any chance those could be merged ? (just for the sake of clearing up my forks :-) )

**Comment by bovender** [comment]
Hi @bertrandgorge, sorry for keeping you waiting so long, I'll very likely will have time next week. And thanks a million for your contributions!

**Comment by bovender** [comment]
Thanks again!
