### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by jmcquillan** [bovender/LinkTitles#8]
When trying to save a page with a "quote" character in the title, it gets the error below:

A database query error has occurred. This may indicate a bug in the software.

Backtrace:

    #0 mediawiki/mediawiki/includes/db/Database.php(1076): DatabaseBase->reportQueryError('You have an err...', 1064, 'SELECT  page_ti...', 'LinkTitles::par...', false)
    #1 mediawiki/mediawiki/includes/db/Database.php(1600): DatabaseBase->query('SELECT  page_ti...', 'LinkTitles::par...')
    #2 mediawiki/mediawiki/extensions/LinkTitles/LinkTitles.body.php(195): DatabaseBase->select('page', 'page_title', Array, 'LinkTitles::par...', Array)
    #3 mediawiki/mediawiki/extensions/LinkTitles/LinkTitles.body.php(68): LinkTitles::parseContent(Object(Title), 'Test')
    #4 [internal function]: LinkTitles::onPageContentSave(Object(WikiPage), Object(User), Object(WikitextContent), '', 0, NULL, NULL, 98, Object(Status))
    #5 mediawiki/mediawiki/includes/Hooks.php(201): call_user_func_array('LinkTitles::onP...', Array)
    #6 mediawiki/mediawiki/includes/page/WikiPage.php(1724): Hooks::run('PageContentSave', Array)
    #7 [internal function]: WikiPage->doEditContent(Object(WikitextContent), '', 98, false, Object(User), 'text/x-wiki')
    #8 mediawiki/mediawiki/includes/page/Article.php(2049): call_user_func_array(Array, Array)
    #9 mediawiki/mediawiki/includes/EditPage.php(1957): Article->__call('doEditContent', Array)
    #10 mediawiki/mediawiki/includes/EditPage.php(1957): Article->doEditContent(Object(WikitextContent), '', 98, false, Object(User), 'text/x-wiki')
    #11 mediawiki/mediawiki/includes/EditPage.php(1331): EditPage->internalAttemptSave(Array, false)
    #12 mediawiki/mediawiki/includes/EditPage.php(560): EditPage->attemptSave(Array)
    #13 mediawiki/mediawiki/includes/actions/EditAction.php(58): EditPage->edit()
    #14 mediawiki/mediawiki/includes/actions/SubmitAction.php(40): EditAction->show()
    #15 mediawiki/mediawiki/includes/MediaWiki.php(490): SubmitAction->show()
    #16 mediawiki/mediawiki/includes/MediaWiki.php(287): MediaWiki->performAction(Object(Article), Object(Title))
    #17 mediawiki/mediawiki/includes/MediaWiki.php(714): MediaWiki->performRequest()
    #18 mediawiki/mediawiki/includes/MediaWiki.php(508): MediaWiki->main()
    #19 mediawiki/mediawiki/index.php(41): MediaWiki->run()
    #20 docroot/index.php(17): require_once('mediawiki/...')
    #21 {main}

**Comment by jmcquillan** [comment]
Would a fix be to wrap LinkTitles::$currentTitle->getDbKey() in addslashes() on line 165 of LinkTitles.body.php?

`addslashes(LinkTitles::$currentTitle->getDbKey())`

**Comment by bovender** [comment]
Yes, thanks.
