### ISSUE TITLE
conflict markers left in code causing syntax error

### ISSUE THREAD

**Issue by jmcquillan** [bovender/LinkTitles#9]
Parse error: syntax error, unexpected '<<' (T_SL), expecting function (T_FUNCTION) in mediawiki/extensions/LinkTitles/includes/LinkTitles_Special.php on line 287

https://github.com/bovender/LinkTitles/blob/master/includes/LinkTitles_Special.php#L287-L291

**Comment by bovender** [comment]
Wow, thanks, how weird. How was it possible to even conclude the merge with unresolved conflicts.

**Comment by bovender** [comment]
It turned out that not only those conflict markers were still in there; a lot of namespace-related code was not included in the merge. That's fixed in v4.0.2.
